-- PromptlyAI: run this whole file once in Supabase SQL Editor
create table if not exists public.prompts (
  id bigint generated by default as identity primary key,
  category text not null,
  title text not null,
  content text not null,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.prompts enable row level security;
grant select on public.prompts to anon, authenticated;
drop policy if exists "Public can read published prompts" on public.prompts;
create policy "Public can read published prompts"
on public.prompts for select
to anon, authenticated
using (published = true);

insert into public.prompts (category,title,content) values
('Study','Explain a difficult topic','Explain [TOPIC] like I am a beginner. Use simple language, one real-life example, five key points, and three quick questions to test me.'),
('Study','Make revision notes','Turn these notes into short revision notes with headings, key terms, formulas if relevant, and a five-question self-test.\n\n[NOTES]'),
('Study','Create a study plan','Turn my goal into a realistic study plan with small daily tasks, revision sessions, and one weekly review.\n\n[GOAL]'),
('Study','Quiz me','Quiz me on [TOPIC] one question at a time. Wait for my answer, then correct it briefly and continue.'),
('Study','Teach with an analogy','Teach [TOPIC] using a simple everyday analogy first, then explain the accurate academic version.'),
('Coding','Debug my code','Act as a patient coding mentor. Find the bug, explain why it happens, show the corrected code, and give one rule to avoid it next time.\n\n[CODE]'),
('Coding','Explain code','Explain this code line by line for a beginner. Define unfamiliar terms and then summarize what the whole program does.\n\n[CODE]'),
('Coding','Build a project plan','Break this software idea into small features, a simple folder structure, and an implementation order suitable for a beginner.\n\n[IDEA]'),
('Coding','Review my code','Review this code for correctness, readability and security. Do not invent problems; explain each real issue and suggest a fix.\n\n[CODE]'),
('Coding','Learn a technology','Create a beginner-friendly learning path for [TECHNOLOGY] with concepts, tiny projects, and checkpoints.'),
('Writing','Make writing clearer','Rewrite the text so it is clear, natural and concise while keeping my original meaning and tone. Then list the three biggest improvements.\n\n[TEXT]'),
('Writing','Write an outline','Create a logical outline for [TOPIC] with an introduction, main sections, supporting points and conclusion.'),
('Writing','Improve grammar','Correct grammar, spelling and awkward wording in this text without changing its meaning.\n\n[TEXT]'),
('Writing','Generate ideas','Give me ten original ideas for [PROJECT]. For each, include the audience, benefit and one simple way to start.'),
('Writing','Summarize text','Summarize this text in five bullet points, then give me one sentence containing the main idea.\n\n[TEXT]'),
('Creative','Brainstorm concepts','Give me 15 varied concepts for [PROJECT]. Avoid repeating the same idea with different wording.'),
('Creative','Create a story idea','Create a unique story premise with a setting, central problem, character goal and an unexpected but logical complication.'),
('Creative','Generate content hooks','Give me 20 short hooks for content about [TOPIC]. Keep them useful, specific and non-clickbait.'),
('Creative','Name a project','Suggest 20 memorable names for [PROJECT]. Explain the strongest five briefly.'),
('Creative','Design a concept','Turn this rough idea into a polished creative concept with style, audience, key elements and execution steps.\n\n[IDEA]'),
('Career','Improve my CV','Improve these CV bullets with clear action verbs and measurable impact where possible. Never invent facts.\n\n[CV BULLETS]'),
('Career','Prepare for an interview','Create ten interview questions for [ROLE] and give concise guidance on what a strong answer should demonstrate.'),
('Career','Write a professional bio','Turn these facts into a concise professional bio. Keep every claim truthful and avoid exaggeration.\n\n[FACTS]'),
('Career','Find skill gaps','Given this target role and my current skills, identify skills I should learn and suggest beginner projects for each.\n\n[ROLE]\n[SKILLS]'),
('Career','Plan a portfolio','Create a portfolio project roadmap for [ROLE] using three projects that demonstrate different practical skills.'),
('Productivity','Plan my next steps','Turn this goal into a simple action plan with the first three actions, likely obstacles and a tiny 15-minute starter task.\n\n[GOAL]'),
('Productivity','Prioritize tasks','Organize these tasks by urgency and importance, explain the reasoning briefly, and suggest the next action for each.\n\n[TASKS]'),
('Productivity','Turn notes into tasks','Turn these messy notes into a clean checklist with specific, actionable tasks.\n\n[NOTES]'),
('Productivity','Weekly review','Help me review my week using wins, unfinished tasks, lessons and three priorities for next week.'),
('Productivity','Simplify a process','Take this process and reduce unnecessary steps while keeping the important safeguards.\n\n[PROCESS]')
on conflict do nothing;

create table if not exists public.tools (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text not null,
  url text not null,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.tools enable row level security;
grant select on public.tools to anon, authenticated;
drop policy if exists "Public can read published tools" on public.tools;
create policy "Public can read published tools"
on public.tools for select
to anon, authenticated
using (published = true);

insert into public.tools (name,category,description,url) values
('ChatGPT','AI Assistant','Chat, learn, brainstorm, write and code.','https://chatgpt.com/'),
('Google Gemini','AI Assistant','General-purpose AI for research, writing and ideas.','https://gemini.google.com/'),
('Claude','AI Assistant','Writing, reasoning and coding assistance.','https://claude.ai/'),
('GitHub','Developer','Code hosting and collaboration for projects.','https://github.com/'),
('Canva','Creative','Design presentations, graphics and social content.','https://www.canva.com/')
on conflict do nothing;
