-- PromptlyAI database setup
create table if not exists public.prompts (
 id bigint generated by default as identity primary key,
 category text not null,
 title text not null,
 content text not null,
 published boolean not null default true,
 created_at timestamptz not null default now()
);
alter table public.prompts enable row level security;
grant select on public.prompts to anon, authenticated;
drop policy if exists "Public can read published prompts" on public.prompts;
create policy "Public can read published prompts" on public.prompts for select to anon, authenticated using (published = true);
insert into public.prompts (category,title,content) values
('Study','Explain anything simply','Explain [TOPIC] like I am a beginner. Use simple language, a real-life example, 5 key points, then give me 3 questions to test my understanding.'),
('Coding','Debug my code','Act as a patient coding mentor. Find the bug in this code, explain why it happens, show the corrected version, and give me one rule to avoid it next time.\n\n[CODE]'),
('Writing','Make my writing clearer','Rewrite the text below so it is clear, natural and concise. Keep my original meaning and tone. Then list the 3 biggest improvements.\n\n[TEXT]'),
('Creative','Generate fresh ideas','Give me 10 original ideas for [PROJECT]. For each, include the target audience, the main benefit and one simple way to start.'),
('Career','Improve my CV','Act as a career writing assistant. Improve these CV bullets using clear action verbs and measurable impact where possible. Do not invent facts.\n\n[CV BULLETS]'),
('Productivity','Plan my next steps','Turn this goal into a simple action plan. Give me the first 3 actions, possible obstacles, and a tiny task I can finish in 15 minutes.\n\n[GOAL]');
