const SUPABASE_URL="https://imcspnvjsvaxzejzxlqr.supabase.co";
const SUPABASE_KEY="sb_publishable_CbYBirWTVCIDHj_79VShxw_zfQKA_4h";
const localPrompts=[
["Study","Explain anything simply","Explain [TOPIC] like I am a beginner. Use simple language, a real-life example, 5 key points, then give me 3 questions to test my understanding."],
["Coding","Debug my code","Act as a patient coding mentor. Find the bug in this code, explain why it happens, show the corrected version, and give me one rule to avoid it next time.\n\n[CODE]"],
["Writing","Make my writing clearer","Rewrite the text below so it is clear, natural and concise. Keep my original meaning and tone. Then list the 3 biggest improvements.\n\n[TEXT]"],
["Creative","Generate fresh ideas","Give me 10 original ideas for [PROJECT]. For each, include the target audience, the main benefit and one simple way to start."],
["Career","Improve my CV","Act as a career writing assistant. Improve these CV bullets using clear action verbs and measurable impact where possible. Do not invent facts.\n\n[CV BULLETS]"],
["Productivity","Plan my next steps","Turn this goal into a simple action plan. Give me the first 3 actions, possible obstacles, and a tiny task I can finish in 15 minutes.\n\n[GOAL]"]];
const toolFallback=[
["ChatGPT","AI Assistant","Chat, learn, brainstorm, write and code.","https://chatgpt.com/"],
["Google Gemini","AI Assistant","Research, writing and everyday AI help.","https://gemini.google.com/"],
["Claude","AI Assistant","Writing, reasoning and coding assistance.","https://claude.ai/"],
["GitHub","Developer","Build, store and collaborate on code.","https://github.com/"],
["Canva","Creative","Create designs, presentations and visual content.","https://www.canva.com/"]];
const state={query:"",category:"All",favorites:JSON.parse(localStorage.getItem("promptly_favorites")||"[]"),copies:JSON.parse(localStorage.getItem("promptly_copies")||"{}"),prompts:localPrompts};
const grid=document.getElementById("promptGrid");
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function loadTools(){const el=document.getElementById("toolList");if(!el)return;let tools=toolFallback;try{const r=await fetch(SUPABASE_URL+"/rest/v1/tools?select=name,category,description,url&published=eq.true&order=created_at.desc",{headers:{apikey:SUPABASE_KEY,Authorization:"Bearer "+SUPABASE_KEY}});if(r.ok){const x=await r.json();if(x.length)tools=x.map(t=>[t.name,t.category,t.description,t.url])}}catch(e){}el.innerHTML=tools.map(t=>'<a class="tool-card" href="'+esc(t[3])+'" target="_blank" rel="noopener"><span class="tag">'+esc(t[1].toUpperCase())+'</span><h3>'+esc(t[0])+' ↗</h3><p>'+esc(t[2])+'</p></a>').join("")}
async function loadRemote(){try{const r=await fetch(SUPABASE_URL+"/rest/v1/prompts?select=category,title,content&published=eq.true&order=created_at.desc",{headers:{apikey:SUPABASE_KEY,Authorization:"Bearer "+SUPABASE_KEY}});if(r.ok){const rows=await r.json();if(rows.length)state.prompts=rows.map(x=>[x.category,x.title,x.content])}}catch(e){}render()}
function copyText(text,button){return navigator.clipboard&&window.isSecureContext?navigator.clipboard.writeText(text):new Promise((resolve,reject)=>{const a=document.createElement("textarea");a.value=text;a.style.position="fixed";a.style.opacity="0";document.body.appendChild(a);a.focus();a.select();try{document.execCommand("copy")?resolve():reject()}catch(e){reject(e)}finally{a.remove()}})}
function render(){const q=state.query.toLowerCase();const data=state.prompts.map((p,i)=>({p,i})).filter(x=>(state.category==="All"||x.p[0]===state.category)&&(!q||x.p.join(" ").toLowerCase().includes(q)));grid.innerHTML=data.length?data.map(x=>{const p=x.p,i=x.i,fav=state.favorites.includes(i);return '<article class="card"><span class="tag">'+esc(p[0].toUpperCase())+'</span><h3>'+esc(p[1])+'</h3><p>'+esc(p[2].replaceAll("\n"," ").slice(0,150))+'…</p><div class="card-actions"><button class="copy" data-copy="'+i+'">Copy prompt</button><button class="favorite" data-fav="'+i+'" aria-label="Favorite prompt">'+(fav?"★":"☆")+'</button></div></article>'}).join(""):'<p class="empty-state">No prompts found. Try another search.</p>';const count=document.getElementById("promptCount");if(count)count.textContent=data.length+" prompts";const popular=state.prompts.slice().sort((a,b)=>(state.copies[state.prompts.indexOf(b)]||0)-(state.copies[state.prompts.indexOf(a)]||0))[0];const pop=document.getElementById("popular");if(pop)pop.textContent=popular?popular[1]:"Ready to explore";bindPromptButtons()}
function bindPromptButtons(){document.querySelectorAll("[data-copy]").forEach(b=>b.onclick=async e=>{e.preventDefault();e.stopPropagation();const i=Number(b.dataset.copy);try{await copyText(state.prompts[i][2],b);state.copies[i]=(state.copies[i]||0)+1;localStorage.setItem("promptly_copies",JSON.stringify(state.copies));b.textContent="✓ Copied!";setTimeout(()=>b.textContent="Copy prompt",1200)}catch(e){b.textContent="Try again";setTimeout(()=>b.textContent="Copy prompt",1200)}});document.querySelectorAll("[data-fav]").forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const i=Number(b.dataset.fav);state.favorites=state.favorites.includes(i)?state.favorites.filter(x=>x!==i):[...state.favorites,i];localStorage.setItem("promptly_favorites",JSON.stringify(state.favorites));render()})}
function detectMode(text,type){const s=(text+" "+type).toLowerCase();if(/image|photo|picture|poster|logo|illustration|art|thumbnail/.test(s))return"image";if(/video|reel|short|animation|cinematic|film/.test(s))return"video";if(/code|website|app|software|python|javascript|html|css/.test(s))return"coding";if(/email|letter|message|caption|post|blog|essay|write/.test(s))return"writing";return"general"}
function buildPrompt(){const idea=document.getElementById("ideaInput").value.trim();const type=document.getElementById("ideaType").value;if(!idea){document.getElementById("builderResult").textContent="Write what you want to create or accomplish first.";return}const mode=detectMode(idea,type);let result="";
if(mode==="image")result="Create this image exactly as described: "+idea+"\n\nVisual direction: photorealistic/high-quality, strong composition, natural lighting, realistic materials and details, clean subject separation, professional color grading.\nOutput: high-resolution image, no unwanted text, no watermark, suitable for the intended platform. Do not ask unnecessary questions; make sensible creative decisions.";
else if(mode==="video")result="Create a polished video based on this concept: "+idea+"\n\nDirection: define the subject, setting, action, camera movement, lens/framing, lighting, atmosphere, pacing and transitions. Keep motion physically consistent and the main subject recognizable throughout.\nOutput: cinematic, coherent, platform-ready video. Make sensible creative decisions instead of asking unnecessary questions.";
else if(mode==="coding")result="Act as a senior software engineer and complete this task: "+idea+"\n\nRequirements: understand the goal, choose a practical solution, provide complete working code, preserve existing functionality when relevant, handle errors and edge cases, and explain only the essential setup steps. Do not leave TODOs or pseudocode where working code is expected.";
else if(mode==="writing")result="Complete this writing task directly: "+idea+"\n\nRequirements: preserve the intended meaning, use natural language, match the requested audience and tone, remove unnecessary filler, and return the finished copy ready to use. Do not explain your process unless specifically requested.";
else result="Act as an expert in the task described below and complete it directly: "+idea+"\n\nRequirements: understand the goal, make reasonable assumptions when details are missing, give a practical finished result, use clear structure, avoid unnecessary questions, and make the output ready to use.";
showBuilderResult(result)}
function improvePrompt(){const input=document.getElementById("fixInput").value.trim();if(!input){document.getElementById("fixResult").textContent="Paste a prompt first.";return}const mode=detectMode(input,"");let result="";
if(mode==="image")result="Create an image based on this request: "+input+"\n\nMake it detailed and ready to paste into an image generator. Specify subject, environment, composition, camera/framing, lighting, materials, mood, style, quality and unwanted elements. Make sensible creative choices and do not ask unnecessary questions.";
else if(mode==="video")result="Create a video based on this request: "+input+"\n\nMake it ready to paste into a video generator. Specify subject, setting, action, camera movement, framing, lighting, motion, pacing, transitions and visual continuity. Make sensible creative choices and do not ask unnecessary questions.";
else result="Complete this task directly and professionally: "+input+"\n\nUse the appropriate role, context, constraints and output format. Preserve the original intention, fill obvious missing details with sensible assumptions, and return the finished result or complete solution rather than discussing how to do it. Do not repeat the user's request and do not ask unnecessary questions.";
showFixResult(result)}
function findTool(mode){const map={image:["Canva","https://www.canva.com/"],video:["Canva","https://www.canva.com/"],coding:["GitHub","https://github.com/"],general:["ChatGPT","https://chatgpt.com/"],writing:["ChatGPT","https://chatgpt.com/"]};return map[mode]||map.general}
function showBuilderResult(t){const el=document.getElementById("builderResult");el.textContent=t;el.classList.add("has-result");const mode=detectMode(document.getElementById("ideaInput").value,document.getElementById("ideaType").value);setResultAction("copyBuilder","builderAction",t,mode)}
function showFixResult(t){const el=document.getElementById("fixResult");el.textContent=t;el.classList.add("has-result");const mode=detectMode(document.getElementById("fixInput").value,"");setResultAction("copyFix","fixAction",t,mode)}
function setResultAction(copyId,actionId,t,mode){const copy=document.getElementById(copyId),action=document.getElementById(actionId),tool=findTool(mode);copy.onclick=()=>copyText(t).then(()=>flash(copy));if(action){action.textContent="Open "+tool[0]+" ↗";action.onclick=()=>window.open(tool[1],"_blank","noopener,noreferrer")}}
function flash(b){const old=b.textContent;b.textContent="✓ Copied!";setTimeout(()=>b.textContent=old,1200)}
document.getElementById("buildBtn").onclick=buildPrompt;document.getElementById("improveBtn").onclick=improvePrompt;
if(!document.getElementById("search"))grid.insertAdjacentHTML("beforebegin",'<div class="prompt-controls"><input id="search" placeholder="Search prompts…" aria-label="Search prompts"><select id="category"><option>All</option><option>Study</option><option>Coding</option><option>Writing</option><option>Creative</option><option>Career</option><option>Productivity</option></select><span id="promptCount"></span></div>');
document.getElementById("search").oninput=e=>{state.query=e.target.value;render()};document.getElementById("category").onchange=e=>{state.category=e.target.value;render()};render();loadRemote();loadTools();